version: '3'

networks:
  web:
    external: true

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    restart: always
    networks:
      - "web"
    command:
      - "--certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
