entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    network: "web"
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "acme.json"
      httpChallenge:
        entryPoint: "http"
